- name: "NetActuate Compute Node"
  na_compute_node:
    hostname: "{{ inventory_hostname }}"
    ssh_public_key: "{{ ssh_public_key }}"
    operating_system: "{{ operating_system }}"
    mbpkgid: "{{ mbpkgid }}"
    location: "{{ location }}"
    state: "{{ state }}"
  register: hostvirtual_device_result
  delegate_to: localhost

-name: "Set Fact ansible_host from device public_ipv4"
  set_fact:
    ansible_host: "{{ hostvirtual_device_result.device.public_ipv4 }}"
